name: CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.tsx'
      - '**.ts'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.tsx'
      - '**.ts'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  optional:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1